class AlreadyAssignedException(Exception):
    pass


class NotAssignedException(Exception):
    pass
